In [1]:
import numpy as np
import pandas as pd

In [2]:
fuel_mix_2017 = pd.read_csv(f'../raw_data_files/fuel_mix/2017_final_fuel_mix.csv')
fuel_mix_2018 = pd.read_csv(f'../raw_data_files/fuel_mix/2018_final_fuel_mix.csv')
marginal_fuels_2017 = pd.read_csv(f'../raw_data_files/fuel_mix/2017_marginal_fuels.csv')
marginal_fuels_2018 = pd.read_csv(f'../raw_data_files/fuel_mix/2018_marginal_fuels.csv')

In [8]:
fuel_mix_df = fuel_mix_2017.append(fuel_mix_2018)
del fuel_mix_df['Marginal']
marginal_fuel_df = marginal_fuels_2017.append(marginal_fuels_2018)
all_df = fuel_mix_df.merge(marginal_fuel_df, on='Begin Date')

In [10]:
all_df.to_csv('fuel_mix_w_marginal.csv')

In [7]:
fuel_mix_df

,Begin Date,Coal,Natural Gas,Nuclear,Hydro,Landfill Gas,Refuse,Solar,Wind,Wood,Oil,Other
0,2017-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-01-01 00:15:00,222.149823,3292.652297,4017.550530,527.149823,27.000000,386.550530,0.0,393.658657,437.003534,0.0,0.0
2,2017-01-01 00:30:00,222.785866,3104.383746,4015.642403,527.785866,27.000000,384.642403,0.0,362.492580,424.282686,0.0,0.0
3,2017-01-01 00:45:00,223.466596,3073.790032,4016.732768,528.466596,27.466596,386.066808,0.0,336.935313,418.066808,0.0,0.0
4,2017-01-01 01:00:00,224.000000,3112.909091,4021.000000,528.662702,27.662702,382.301614,0.0,318.964316,416.325404,0.0,0.0
5,2017-01-01 01:15:00,224.000000,3042.684411,4020.771863,528.000000,27.000000,377.342205,0.0,311.859316,414.201521,0.0,0.0
6,2017-01-01 01:30:00,224.000000,3047.817490,4019.060837,528.000000,27.000000,379.908745,0.0,303.304183,408.212928,0.0,0.0
7,2017-01-01 01:45:00,222.293976,2915.701205,4017.000000,527.000000,27.646988,387.293976,0.0,291.469880,415.118072,0.0,0.0
8,2017-01-01 02:00:00,220.005479,2915.267123,4017.497260,527.000000,27.000000,384.508219,0.0,278.535616,416.016438,0.0,0.0
9,2017-01-01 02:15:00,220.537500,2873.950000,4018.512500,526.487500,27.000000,381.462500,0.0,266.875000,421.712500,0.0,0.0
10,2017-01-01 02:30:00,221.463847,2742.529332,4016.855389,526.536153,27.000000,384.825375,0.0,262.536153,431.072306,0.0,0.0
11,2017-01-01 02:45:00,222.639824,2824.266471,4016.639824,527.000000,27.000000,386.540264,0.0,267.099561,422.980966,0.0,0.0
12,2017-01-01 03:00:00,220.780142,2658.460993,4018.219858,516.390071,27.000000,387.170213,0.0,263.829787,424.659574,0.0,0.0
13,2017-01-01 03:15:00,221.509579,2664.057471,4016.509579,517.000000,27.000000,389.490421,0.0,255.624521,419.038314,0.0,0.0
14,2017-01-01 03:30:00,221.473535,2642.532136,4016.000000,517.947070,27.000000,388.579395,0.0,247.579395,413.211720,0.0,0.0
15,2017-01-01 03:45:00,221.578106,2693.300123,4016.000000,519.000000,27.000000,385.312423,0.0,248.531365,404.781058,0.0,0.0
16,2017-01-01 04:00:00,221.554839,2746.612903,4016.554839,534.535484,27.000000,385.774194,0.0,253.664516,405.658065,0.0,0.0
17,2017-01-01 04:15:00,220.793478,2709.190217,4015.793478,547.000000,27.000000,388.603261,0.0,261.635870,411.000000,0.0,0.0
18,2017-01-01 04:30:00,220.000000,2718.901254,4015.838558,546.161442,27.000000,390.677116,0.0,265.161442,404.291536,0.0,0.0
19,2017-01-01 04:45:00,221.397366,2730.668496,4016.807903,544.205269,27.000000,386.192097,0.0,270.000000,403.165752,0.0,0.0
20,2017-01-01 05:00:00,222.000000,2709.515625,4014.634375,543.000000,27.000000,387.634375,0.0,270.365625,412.462500,0.0,0.0
21,2017-01-01 05:15:00,221.590141,2738.526761,4015.229577,543.000000,27.000000,390.278873,0.0,275.918310,415.409859,0.0,0.0
22,2017-01-01 05:30:00,223.329298,2790.506053,4018.746973,587.838983,27.000000,389.759080,0.0,283.000000,420.658596,0.0,0.0
23,2017-01-01 05:45:00,222.970750,2825.541133,4018.985375,628.117002,27.000000,390.058501,0.0,286.551188,421.970750,0.0,0.0
24,2017-01-01 06:00:00,222.045367,2901.723938,4017.651544,644.014479,27.000000,390.863900,0.0,300.453668,423.136100,0.0,0.0
25,2017-01-01 06:15:00,224.392670,3002.701571,4016.607330,659.785340,27.000000,385.000000,0.0,320.785340,431.748691,0.0,0.0
26,2017-01-01 06:30:00,225.985714,3052.871429,4017.971429,661.000000,27.000000,391.900000,0.0,341.714286,432.057143,0.0,0.0
27,2017-01-01 06:45:00,225.890411,3182.945205,4019.945205,662.260274,27.000000,388.000000,0.0,365.328767,416.945205,0.0,0.0
28,2017-01-01 07:00:00,223.620690,2751.517241,4013.241379,649.344828,27.000000,393.931034,0.0,384.310345,414.758621,0.0,0.0
29,2017-01-01 07:15:00,223.985455,2686.956364,4017.992727,679.000000,27.000000,388.978182,0.0,420.883636,429.050909,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
35010,2018-12-31 16:30:00,0.149047,6091.634315,4014.223570,1905.783362,25.000000,364.000000,0.0,211.466205,351.000000,0.0,0.0
35011,2018-12-31 16:45:00,0.000000,6268.605839,4015.051095,1910.708029,25.000000,362.744526,0.0,243.510949,354.948905,0.0,0.0
35012,2018-12-31 17:00:00,0.000000,6261.956616,4016.813449,2010.891540,25.000000,358.813449,0.0,259.778742,353.186551,0.0,0.0
35013,2018-12-31 17:15:00,0.000000,6108.066914,4018.152416,2161.104089,25.000000,361.565056,0.0,285.910781,351.565056,0.0,0.0
35014,2018-12-31 17:30:00,0.000000,6083.507119,4016.000000,2175.279299,25.000000,363.000000,0.0,318.305586,353.351588,0.0,0.0
35015,2018-12-31 17:45:00,0.000000,6062.644068,4016.372881,2102.135593,25.000000,362.254237,0.0,348.830508,356.983051,0.0,0.0
35016,2018-12-31 18:00:00,0.000000,6093.872587,4016.262548,1944.007722,25.000000,360.262548,0.0,347.250965,356.837838,0.0,0.0
35017,2018-12-31 18:15:00,0.000000,5862.000000,4014.000000,1903.000000,25.000000,355.000000,0.0,361.000000,357.000000,0.0,0.0
35018,2018-12-31 18:30:00,3.620253,5879.987342,4017.987342,1783.075949,25.000000,361.493671,0.0,375.481013,353.000000,0.0,0.0
35019,2018-12-31 18:45:00,1.819967,5609.497545,4015.726678,1765.459902,25.000000,363.273322,0.0,388.540098,355.453355,0.0,0.0
35020,2018-12-31 19:00:00,6.000000,5635.193548,4016.000000,1642.387097,25.000000,355.612903,0.0,407.903226,361.419355,0.0,0.0
35021,2018-12-31 19:15:00,3.000000,5644.251572,4013.327044,1509.278826,25.000000,357.211740,0.0,435.501048,351.345912,0.0,0.0
35022,2018-12-31 19:30:00,2.953737,5532.355872,4014.000000,1340.676157,25.000000,358.138790,0.0,440.676157,357.092527,0.0,0.0
35023,2018-12-31 19:45:00,2.000000,5314.736842,4016.736842,1332.175439,25.000000,361.912281,0.0,431.263158,355.350877,0.0,0.0
35024,2018-12-31 20:00:00,2.251232,5282.847291,4013.502463,1332.753695,25.000000,361.497537,0.0,453.995074,356.497537,0.0,0.0
35025,2018-12-31 20:15:00,0.626685,5241.858491,4016.000000,1203.626685,25.000000,363.253369,0.0,472.586253,355.506739,0.0,0.0
35026,2018-12-31 20:30:00,0.000000,4948.039216,4014.294118,1202.901961,25.000000,364.313725,0.0,487.823529,353.294118,0.0,0.0
35027,2018-12-31 20:45:00,2.210682,4778.801187,4016.000000,1202.596439,25.000000,357.175074,0.0,481.560831,352.614243,0.0,0.0
35028,2018-12-31 21:00:00,0.269283,4441.565629,4012.346414,1162.146143,25.000000,363.730717,0.0,478.423545,353.000000,0.0,0.0
35029,2018-12-31 21:15:00,0.060052,4229.422977,4016.000000,1053.060052,25.000000,367.699739,0.0,496.279373,354.879896,0.0,0.0
35030,2018-12-31 21:30:00,0.000000,4203.821053,4017.000000,1057.824060,25.000000,361.527820,0.0,500.574436,352.175940,0.0,0.0
35031,2018-12-31 21:45:00,2.983051,3933.271186,4017.000000,1058.491525,25.000000,360.271186,0.0,540.644068,354.491525,0.0,0.0
35032,2018-12-31 22:00:00,1.814249,3838.063613,4016.185751,1018.778626,25.000000,359.628499,0.0,548.256997,352.185751,0.0,0.0
35033,2018-12-31 22:15:00,0.000000,3610.929155,4017.000000,1020.765668,25.000000,361.297003,0.0,512.008174,353.531335,0.0,0.0
35034,2018-12-31 22:30:00,0.000000,3641.864215,4018.239038,1019.000000,25.000000,354.619519,0.0,511.282885,352.619519,0.0,0.0
35035,2018-12-31 22:45:00,0.000000,3472.110891,4014.255446,1016.255446,25.000000,363.148515,0.0,514.085149,351.085149,0.0,0.0
35036,2018-12-31 23:00:00,0.000000,3256.360656,4015.508197,1190.377049,26.000000,359.245902,0.0,553.622951,354.754098,0.0,0.0
35037,2018-12-31 23:15:00,0.000000,3039.561828,4012.220430,1473.258065,26.000000,354.889785,0.0,578.102151,357.661290,0.0,0.0
35038,2018-12-31 23:30:00,0.000000,2805.641379,4014.000000,1545.537931,26.000000,354.000000,0.0,614.082759,365.462069,0.0,0.0
35039,2018-12-31 23:45:00,0.000000,2544.498925,4016.591398,1471.326882,26.000000,357.019355,0.0,660.447312,365.918280,0.0,0.0